version: "3.9"

services:
  db:
    image: postgres:15
    container_name: agrismart-db
    environment:
      POSTGRES_USER: agrismart
      POSTGRES_PASSWORD: agrismart_pass
      POSTGRES_DB: agrismart_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    container_name: agrismart-redis
    ports:
      - "6379:6379"
    restart: always

  # backend:
  #   build: ../backend
  #   container_name: agrismart-backend
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - "8080:8080"
  #   restart: always

  # admin:
  #   build: ../admin
  #   container_name: agrismart-admin
  #   ports:
  #     - "3000:3000"
  #   restart: always

volumes:
  db_data:

